name: Build

on: [push]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32OlcbIO, ESP32OlcbIO-WiFiOff]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update config For WiFi=OFF
        if: ${{ matrix.target == 'ESP32OlcbIO-WiFiOff' }}
        uses: DamianReeves/write-file-action@master
        with:
          path: sdkconfig.defaults
          contents: |
            CONFIG_WIFI_MODE_OFF=y
          write-mode: append
      - name: Build
        uses: atanisoft/esp-idf-ci-action@master
        with:
          path: firmware
      - name: Prepare Binaries
        run: |
          mkdir -p firmware/binaries
          cp .github/firmwarereadme.txt firmware/binaries
          cd firmware
          idf.py reconfigure
          idf.py build
          idf.py size
          cp build/ESP32OlcbIO.bin binaries
          cp build/partition_table/partition-table.bin binaries
          cp build/ota_data_initial.bin binaries
          cp build/bootloader/bootloader.bin binaries
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: firmware/binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
