name: Build

on: [push]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32OlcbIO, ESP32OlcbIO-WiFiOff, ESP32OlcbIO-PWM]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update config For WiFi=OFF
        if: ${{ matrix.target == 'ESP32OlcbIO-WiFiOff' }}
        uses: DamianReeves/write-file-action@master
        with:
          path: firmware/sdkconfig.defaults
          contents: |
            CONFIG_WIFI_MODE_OFF=y
          write-mode: append
      - name: Update config For PWM
        if: ${{ matrix.target == 'ESP32OlcbIO-PWM' }}
        uses: DamianReeves/write-file-action@master
        with:
          path: firmware/sdkconfig.defaults
          contents: |
            CONFIG_OLCB_ENABLE_PWM=y
          write-mode: append
      - name: Build
        uses: atanisoft/esp-idf-ci-action@master
        with:
          path: firmware
      - name: Prepare Binaries
        run: |
          mkdir -p binaries
          cp .github/firmwarereadme.txt binaries/readme.txt
          cp firmware/build/ESP32OlcbIO.bin binaries
          cp firmware/build/partition_table/partition-table.bin binaries
          cp firmware/build/ota_data_initial.bin binaries
          cp firmware/build/bootloader/bootloader.bin binaries
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}
          path: binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
