name: Build

on: [push]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32OlcbIO, ESP32OlcbIO-WiFiOff]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'release/v4.2'
      - name: Update config For WiFi=OFF
        if: ${{ matrix.target == 'ESP32OlcbIO-WiFiOff' }}
        uses: DamianReeves/write-file-action@master
        with:
          path: sdkconfig.defaults
          contents: |
            CONFIG_WIFI_MODE_OFF=y
          write-mode: append
      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          cd firmware
          idf.py reconfigure
          idf.py build
          idf.py size
          mkdir binaries
          cp build/ESP32OlcbIO.bin binaries
          cp build/partition_table/partition-table.bin binaries
          cp build/ota_data_initial.bin binaries
          cp build/bootloader/bootloader.bin binaries
      - name: Create readme.txt for binary
        uses: DamianReeves/write-file-action@master
        with:
          path: binaries/readme.txt
          contents: |
            The binaries can be sent to the ESP32 via esptool.py similar to the following:
            python esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset
                write_flash 0x1000 bootloader.bin
                write_flash 0x8000 partition-table.bin
                write_flash 0xe000 ota_data_initial.bin
                write_flash 0x10000 Esp32OlcbIO.bin
            Note: The esptool.py command above should be all on one line.
            If you prefer a graphical utility for flashing you can use the Flash Download Tool
            available from https://www.espressif.com/en/support/download/other-tools to write
            the four binary files listed above at the listed offsets.
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ESP32OlcbIO
          path: firmware/binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
